/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api.teste;

import org.apache.http.HttpStatus;
import org.junit.Test;
import qaops.automation.api.dominio.Usuario;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class TesteUsuario extends TesteBase {

    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIAR_USUARIO_ENDPOINT = "/user";

    // Primeiro teste: Listagem de usuário
    @Test
    public void testeListaPaginaDeUsuarios() {
        given().params("page", "2"). // Define paramentros da página
        when(). // Quando
            get(LISTA_USUARIOS_ENDPOINT). // fazer get no endereço
        then(). //Então
            //SC_OK = 200
            statusCode(HttpStatus.SC_OK). // Verifica o status code para ver se funcionou
            body("page", is(2)). // Verifica se está na página 2
            body("data", is(notNullValue())); // Verifica se array não veio vazio
    }

    //Segundo Teste: Criação de Usuário
    @Test
    public void testeCriarUsuarioComSucesso() {
        Usuario usuario = new Usuario("rafael","eng test", "email@gmail.com"); // Cria usuário
        given().
            body(usuario). // Envia usuario criado
        when(). // diz qual será a ação
            post(CRIAR_USUARIO_ENDPOINT). // post nesse endereço
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("rafael"));
    }
}

// Se rodar ./gradlew test no terminal todos os testes seram executados

// Serializar => Tranformar objeto java em JSON