/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api;

import org.junit.Test;

import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

public class AppTest {

    // Primeiro teste
    @Test
    public void testeListaMetadosDoUsuario() {
        when(). // Quando
            get("https://reqres.in/api/users?page=2"). // fazer get no endereço
        then(). //Então
            statusCode(200) // Verigica o status code para ver se funcionou
            .body("page", is(2)) // Verifica se está na página 2
            .body("per_page", is(6)) // Verifica quantidade de elementos na página
            .body("data[0].email", is("michael.lawson@reqres.in")); // Verifica email do primeiro item do array
    }
}
