/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static io.restassured.RestAssured.when;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class AppTest {

    // Primeiro teste
    @Test
    public void testeListaMetadosDoUsuario() {
        when(). // Quando
            get("https://reqres.in/api/users?page=2"). // fazer get no endereço
        then(). //Então
            //SC_OK = 200
            statusCode(HttpStatus.SC_OK). // Verifica o status code para ver se funcionou
            body("page", is(2)). // Verifica se está na página 2
            body("data", is(notNullValue())); // Verifica se array não veio vazio
    }

    @Test
    public void testeCriarUsuarioComSucesso() {
        given().
            contentType(ContentType.JSON). // Dfinindo que será enviado um JSON
            body("{\"name\": \"rafael\", \"job\": \"eng test\"}"). // Enviando JSON
        when(). // diz qual será a ação
            post("https://reqres.in/api/users"). // post nesse endereço
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("rafael"));
    }
}
