/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qaops.automation.api;

import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class AppTest {

    @BeforeClass
    public static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails(); // Define para log seja mais verboso e facil de entender.
        baseURI = "https://reqres.in"; // Define url base de todos os testes
        basePath = "/api";  // define caminho base de todos os testes
    }

    // Primeiro teste: Listagem de usuário
    @Test
    public void testeListaMetadosDoUsuario() {
        given().params("page", "2"). // Define paramentros da página
        when(). // Quando
            get("/users"). // fazer get no endereço
        then(). //Então
            //SC_OK = 200
            statusCode(HttpStatus.SC_OK). // Verifica o status code para ver se funcionou
            body("page", is(2)). // Verifica se está na página 2
            body("data", is(notNullValue())); // Verifica se array não veio vazio
    }

    //Segundo Teste: Criação de Usuário
    @Test
    public void testeCriarUsuarioComSucesso() {
        given().
            contentType(ContentType.JSON). // Definindo que será enviado um JSON
            body("{\"name\": \"rafael\", \"job\": \"eng test\"}"). // Enviando JSON
        when(). // diz qual será a ação
            post("/users"). // post nesse endereço
        then().
            statusCode(HttpStatus.SC_CREATED).
            body("name", is("rafael"));
    }
}

// Se rodar ./gradlew test no terminal todos os testes seram executados